### ISSUE TITLE
Create project structure

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/bubble_scan#1]
The first step to this project is to define the structure - how the code will be broken up in various modules (defined by directories) and define how the directories will interact with each other. 

Since this project will use an AI module, developed by another team, using Python for interacting with the AI module seems like a reasonable approach. There should also be a web API for accessing the features built as part of this project. 

I suggest to follow the "Clean Architectures in Python" approach for defining the API and functionality provided through this API: https://leanpub.com/clean-architectures-in-python

For user interactions, any front-end framework would work (I do not recommend using Python for the front-end). React, for example, is a reasonable choice.

This issue is broken up into smaller issues

- [x] issue #2 
- [x] issue #3
- [x] issue #4

**Comment by rkarmuri** [comment]
A well-defined project structure is built.
