### ISSUE TITLE
Upload images on the client component

### ISSUE THREAD

**Issue by rkarmuri** [oss-slu/bubble_scan#13]
We are combining all students' scantron sheets into a PDF file. Therefore the user can upload the inputData/exampleScans.pdf file through the user interface. We are to restrict uploading any other file formats on the user interface.

Success criteria for this issue:

- [x] The react component allows users to upload files to the server component.
- [x] No CORS issues should occur during the file upload process. 
- [x] The server component acknowledges that the files are uploaded successfully.
- [x] The UI doesn't allow users to upload other file formats.

**Comment by yildizahmetali** [comment]
Finished this issue

**Comment by rkarmuri** [comment]
That's good work, Ahmet. You styled the home page pretty well. I can upload only PDF documents and that is what we want.

**Comment by rkarmuri** [comment]
The user can upload the inputData/exampleScans.pdf file through the user interface. We can restrict uploading any other file formats on the user interface. The files are transferred to the server component successfully.
