### ISSUE TITLE
Server component of the project

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/bubble_scan#2]
This issue is part of issue #1 

The server component will provide web API access to the scoring/grading features defined by this project. This component will interact with the AI module, that will "read" the input images/files and give back the tabulated results. Before defining the details of the implementation, we need to set up the server component and its structure. Creating the server side in Python will simplify interactions with the AI module (which will most likely be in Python). Follow the "Clean Architectures in Python" as a guide for setting up the server side: https://leanpub.com/clean-architectures-in-python

Success Criteria for resolving this issue:

- [x] High level component, server, exists in the project repository
- [x] The server component provides access to a web API
- [x] There are clear instructions in the form of a README.md file specifying how to start the server
- [x] The server is broken up into smaller sub-components, following the "Clean Architectures in Python" approach (application, domains, serializers, use_cases).
- [x] The server works with the client component, as defined in issue #3 
- [x] A .gitignore file, appropriate for the server-side tech, is included in the server directory

**Comment by rkarmuri** [comment]
Connection is established between the client and the server.
