### ISSUE TITLE
Client component of the project

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/bubble_scan#3]
This issue is part of issue #1 

The client component will provide the user with a web browser based user interface for input and output, and will interact with the server component (as defined in issue #2) to submit user inputs and to receive outputs. The client component needs to be in a separate directory from the server. There are several frameworks for building client-side components, React might be a good option (other options may be just as good).

Success criteria for this issue:

- [x] High level component, client, exists in the project as a separate directory
- [x] The client component provides a browser based user interface - allowing the user to enter input (any dummy input is fine for nwo)
- [x] There are clear instructions in the form of a README.md file specifying how to start the client
- [x] The client provides a way to submit user input to the server, as defined in issue #2 
- [x] A .gitignore file, appropriate for the client side tech, is included in the client directory

**Comment by rkarmuri** [comment]
Server and client components can communicate with each other.
