### ISSUE TITLE
Mock AI component

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/bubble_scan#4]
This issue is part of issue #1 

The machine vision (AI) part of this project will be developed by another team, in parallel. To better understand how our application will interact with the AI module and allow parallel development, we can build a mock AI module that the server component, as defined in issue #2, will interact with for now. When the real AI module becomes available, we'll replace the mock AI component with the real AI module.

Success Criteria for resolving this issue

- [x] High level component, ai_grader, exists in the project repository (the name ai_grader can be changed to something else, but something descriptive of the component's purpose)
- [x] The component defines an interface for sending input file (pdf or image format) 
- [x] The component provides a mock student id and mock answers for each input file  as a response (in the form of a list of answers for each question. For example: a, c, -, b, d, ...).
- [x] The mock response is defined in a file (simple text file would work).
- [x] The component works with the server component, as defined in issue #2, to provide mock responses for grading requests.

**Comment by rkarmuri** [comment]
The mock AI given here is irrelevant and the mock AI has been changed to meet the needs of the client's requirement. The mock AI is built to generate Student IDs, and their answers in a JSON format as discussed with the client and AI team.
