### ISSUE TITLE
Project summary in README

### ISSUE THREAD

**Issue by kungfuchicken** [oss-slu/bubble_scan#40]
In the README file, please provide a brief overview of the project. The overview should explain what we are doing in this project from a user perspective. Detail the steps required to run the code effectively. This should include instructions on setting up the development environment, installing dependencies, and starting the frontend and backend servers. Have an architectural diagram of the program on how it is set up. Additionally, guides on uploading a scantron document, initiating the scanning process, and retrieving the generated CSV file. Finally, remove unnecessary files and folders within the project.

Success criteria:
- [x] Detailed steps for setting up the development environment, including any prerequisite software or tools are provided.
- [x] Removed unnecessary files and folders and structured the project neatly.
- [x] Clear guidance on installing front and backend component dependencies.
- [x] Instructions for starting the frontend and backend servers, including any configuration settings or environment variables are provided.
- [x] A step-by-step process for uploading a scantron document, initiating the scanning process, and retrieving the generated CSV file is provided.
- [x] An architectural diagram is provided to show the software design.

**Comment by rkarmuri** [comment]
A detailed overview of the project is explained. Removed unnecessary files and folders and structured the project neatly. Clear guidance on installing front and backend component dependencies is provided. Instructions for starting the frontend and backend servers, including any configuration settings or environment variables are provided.  A step-by-step process for uploading a scantron document, initiating the scanning process, and retrieving the generated CSV file is provided using an architectural diagram.
