### ISSUE TITLE
Update README to Include Custom Sheet Processing Roadmap

### ISSUE THREAD

**Issue by Chirag2x** [oss-slu/bubble_scan#68]
Description: As we continue developing the BubbleScan project, it’s important to keep the README file up to date with our progress and future plans. Currently, the README lacks information about our next development phase: supporting custom sheet processing. This issue focuses on adding a section to the README that outlines the planned features for custom sheet compatibility, along with any relevant notes about its development.

Goal:
Update the project’s README file to include a clear roadmap for the upcoming custom sheet processing feature. This will help future contributors understand the direction of the project and what features are expected to be implemented.
Tasks:

Add a section titled "Upcoming Features: Custom Sheet Processing" to the README.
Provide a brief description of the planned feature and its significance to the project.
List the key development milestones for implementing custom sheet processing (e.g., research, algorithm development, frontend modifications).
Ensure the new section is formatted properly and fits with the existing structure of the README.

Success Criteria:
The README file is updated with a clear and concise section on the custom sheet processing feature.

**Comment by kate-holdener** [comment]
@Chirag2x @kungfuchicken @mylescorrea Wouldn't it be better to keep the list of necessary features as GitHub issues instead of the README.md file?

**Comment by kate-holdener** [comment]
@Chirag2x Should this issue be closed as "Not planned"?

**Comment by kungfuchicken** [comment]
you need to capture this, but README might not be best; i agree with @kate-holdener . Issues go in Issues, even if they are "big rocks" or rough sketches of what we know when we create it. We should probably capture the overall product roadmap in a format that is better suited, and we have some options for that.
