### ISSUE TITLE
Custom Sheet Testing

### ISSUE THREAD

**Issue by Chirag2x** [oss-slu/bubble_scan#82]
Description: We want to incorporate custom sheets which can be scanned by Scantron AI Algorithms.

Given our Ai API
when custom sheets are submitted 
then it should result in efficiently extracted csv file.

Developer Notes: 
You have to modify BubbleScan Ai directory.

Success Criteria:
 
- [x] #97
- [x] #104
- [x] Returns CSV files.
- [x] At least 98% Accuracy for the custom sheets wrt Ground Truth.

**Comment by kate-holdener** [comment]
@Chirag2x Do we want to confirm the format of the custom sheet with the client, before we proceed with this issue?

**Comment by Chirag2x** [comment]
> @Chirag2x Do we want to confirm the format of the custom sheet with the client, before we proceed with this issue?

I can confirm with him the design by Friday will schedule a meeting. But I guess we should go ahead with the backend implementation, since we have almost accommodated all of his requirements regarding the custom sheet looks. Do you want us to wait we can do that.?
