### ISSUE TITLE
Add a Homepage with Welcome Message and Application Overview

### ISSUE THREAD

**Issue by Chirag2x** [oss-slu/bubble_scan#90]
Description: As part of our Hacktoberfest participation, we want to enhance the user experience by adding a dedicated homepage to the BubbleScan application. The homepage will act as a welcome page and provide users with an overview of what the application does and how to use it.

This task involves creating a simple, attractive homepage that explains the purpose of BubbleScan, welcomes new users, and provides navigation to key features like uploading files, creating custom sheets, and viewing results.

Tasks:

Create Homepage:
Design and implement a homepage that fits within the existing React frontend.
Include a welcoming headline, such as "Welcome to BubbleScan!"
Add a brief description of what BubbleScan does (e.g., "BubbleScan is a tool designed to process scantron sheets, allowing users to upload PDFs, generate results, and create custom sheets for their exams.").

Design Considerations:
Ensure the homepage follows the same design theme as the rest of the application.
Make it responsive so that it works well on both desktop and mobile devices.
Optionally, add a simple graphic or icon to enhance the visual appeal.
Content:
Briefly explain the core functionalities of the application (uploading PDFs, generating results, custom sheet creation).
Provide a "How to Get Started" section that guides users on where to go first.
Expected Outcome:

A fully functional, visually appealing homepage that introduces users to BubbleScan and provides them with easy navigation to core features.
The homepage should be integrated into the current app and accessible when visiting the root URL (/).

**Comment by Sreeeja9866** [comment]
I will work on this issue
