### ISSUE TITLE
Add Navigation Bar with options to Home, Upload Sheets, Create Custom Sheets, and About Us

### ISSUE THREAD

**Issue by Chirag2x** [oss-slu/bubble_scan#91]
Description: As part of our effort to improve user experience and site navigation, we need a navigation bar (nav bar) that will allow users to easily move between different sections of the BubbleScan application. This task involves designing and implementing a simple, responsive nav bar that fits within the current application design.

Tasks:

Design and Implement Nav Bar:
Add a responsive navigation bar at the top of the application.
The navigation bar should include # links to:
Home: Redirects to the homepage (root /).
Upload Sheets: Links to the page where users can upload their scantron sheets.
Create Custom Sheets: Links to the custom sheet creation page.
About Us: A page where users can learn more about the project, team, and its purpose.

Styling:
Ensure that the navigation bar follows the current styling theme of the app.
Make sure it is responsive and displays well on mobile and desktop screens.
Highlight the current active page in the nav bar for better UX.

Expected Outcome:
A functional, user-friendly navigation bar that allows users to quickly access key sections of the app.
Proper styling and responsiveness, ensuring a seamless experience across different screen sizes.

**Comment by SowmyaKoneti** [comment]
I will work on this issue
