### ISSUE TITLE
Create Dataset for testing: Ground Truth

### ISSUE THREAD

**Issue by Chirag2x** [oss-slu/bubble_scan#92]
We have to create Ground truth dataset for custom sheets, so we can test the performance of custom sheets with this help of this. This requires to create the true answers for the scans that was sent by Dr. Holdener in project channel (for testing ai results).
This issue would need to manually go through each sheet and generate a CSV version of the answers. You will need to set up way to compare the true answers with AI produced answers.
set up a script that takes 2 Input CSV, 1 for true answer that you created and other will be output from bubble scan, compares against the true answers.

Success Criteria:
- [x] Set up the comparison scripts.
- [x] Get the output in digital format.
- [ ] Then scan those with our application for accuracy.
- [ ] Then compare the output with your comparison scripts.
- [ ] Report the results and misses.

Data:
[bubble_scans_50_5.pdf](https://github.com/user-attachments/files/17479271/bubble_scans_50_5.pdf)

**Comment by kate-holdener** [comment]
This would be great for new contributors! Let's make sure we have the custom sheet format finalized before beginning this work.

**Comment by Chirag2x** [comment]
> This would be great for new contributors! Let's make sure we have the custom sheet format finalized before beginning this work.

I wanted this to be a group activity. so this can be used to check the accuracy for the custom sheets.

**Comment by yildizahmetali** [comment]
Here is the CSV file for all student answers: [bubble_scan_answers_50.csv](https://github.com/user-attachments/files/17542790/bubble_scan_answers_50.csv)
