### ISSUE TITLE
Flask api deployment with AWS Lambda

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/bubble_scan#94]
To minimize the cost of hosting the application, we want the ability to deploy the backend API as an AWS Lambda function. This deployment should be "reusable" meaning, there is a configuration file that defines the deployment steps.

This typically requires creating a serverless.yml file defining the deployment, and making some adjustments to the flask application.

Success criteria

- [ ] backend api can be deployed with one command: serverless deploy
- [ ] The command results with a URL that can be used to access the backend api

**Comment by Chirag2x** [comment]
@kate-holdener 
we already have an issue for deployment.

**Comment by mylescorrea** [comment]
### Lambda Issue will not work with our program.

Lambda has many qualifications in order for it to work. These include memory ranges (10 mb zipped), minimum numbers of Lambda layers, and a limited file system. Unfortunately, our program has over all of these. The program is about 600 mb unzipped, we would need more than just 5 Lambda layers, and we use an extensive file system to interpret the scantrons for grading. 

### What was tried
I tried several different avenues but all of them lead to another problem. Towards the end I was just deleting too many elements that made me believe our project would not run correctly even if we got it down to the reasonable size. Here are the attempts I tried to get the sizing of the folder down to Lambda's specifications:
1.	Deleted all unnecessary files in ServerCode folder
a.	Only left with application, bubbleScan, mockapp, requirements.txt
b.	**Result:** Zip file was small enough but was missing essential libraries to run tests

2.	Downloaded all libraries and included them in zip file
a.	**Result:** Zip file was now too big, around 900 mb

3.	Deleted all unused libraries in requirements.txt and only installed the necessary ones
a.	I was only left with Flask, Flask-Cors, numpy, opencv-python, PyMuPDF, PyPDF2, Wekzeug
b.	**Result:** Still too big, but trimmed to only 94 MB zipped

4.	Adding all libraries into a lambda layer
a.	Zipped the necessary libraries and tried to make a lambda layer with them
b.	**Result:** Too big for lambda layer

5.	Deleted unnecessary files from libraries
a.	Deleted tests, documentation, metadata
b.	**Result:** Still too big for layer

6.	Splitting libraries to separate lambda layers
a.	Separate the libraries into 2 zip files each
b.	**Result:** First layer worked, but second layer was still too big

7.	Split the second lambda layer into sub layers
a.	Split numpy, opencv-python, and PyMuPDF into separate layers
b.	**Result:** numpy and PyMuPDF could be put into layers, but opencv-python was still too big

8.	Find precompiled Lambda layer for opencv-python
a.	Tried to find pre-built Lambda layers for opencv
b.	**Result:** They were all too big and required Amazon S3

### For the future
Now we will try deployment of a desktop application using Flaskwebgui. As of my research there are no big limitations that will stop us from using our program this way. There also does not seem to be any costs with running our application. The only obstacle I may see coming is that it limits access to native desktop features like file explorer. This is concerning with knowing that the users have to upload their scantrons sheets from most likely file explorer. I will try and implement this way and see how it goes.
